### PR TITLE
Added DC Fan control

### PR DESCRIPTION
**Pull request by faisalhusain007**
Common.py added BCM pin 26 for PWM output control of Fan 
Grillplat_pifire.py added control of 12V DC fan; added functionality for variable fan speed based on  grill temperature; added functionality for ramp fan for smoke plus mode .

### CODE REVIEW

**Comment by faisalhusain007** [comment]
I have done plenty of testing on my bench rig, seems to work without breaking anything but would advise some quick checks on my code and testing .

**Review by nebhead — CHANGES_REQUESTED** [review]
Hey, these changes look good, but can we move the grillplat_pifire.py changes into a new file.  Suggest you use something like grillplat_pifire_dcfan.py.  This way, we can ensure that these changes to affect current users.  You can still load the right module by modifying your control.py to load this file instead of the original.

**Comment by ryanmurray** [comment]
> Common.py added BCM pin 26 for PWM output control of Fan Grillplat_pifire.py added control of 12V DC fan; added functionality for variable fan speed based on grill temperature; added functionality for ramp fan for smoke plus mode .

So what kinda fan you using :)

**Comment by faisalhusain007** [comment]
> Hey, these changes look good, but can we move the grillplat_pifire.py changes into a new file. Suggest you use something like grillplat_pifire_dcfan.py. This way, we can ensure that these changes to affect current users. You can still load the right module by modifying your control.py to load this file instead of the original.

I can, however the changes I made shouldn't affect current users since to use the DC Fan you will need to amend the current control.py to use the new objects in grillplat. VarFanON and FanRamp. These will not get used unless we change the control to point at them replace FanOn and FanToggle. I am cool either way, let me know what you think.

**Comment by faisalhusain007** [comment]
> > Common.py added BCM pin 26 for PWM output control of Fan Grillplat_pifire.py added control of 12V DC fan; added functionality for variable fan speed based on grill temperature; added functionality for ramp fan for smoke plus mode .
> 
> So what kinda fan you using :)
image

image

**Comment by ryanmurray** [comment]
> > > Common.py added BCM pin 26 for PWM output control of Fan Grillplat_pifire.py added control of 12V DC fan; added functionality for variable fan speed based on grill temperature; added functionality for ramp fan for smoke plus mode .
> > 
> > So what kinda fan you using :)
> image
> 
> image
> 

So are you running the fan at 5 volts or?

**Review by nebhead — COMMENTED** [review]
OK, let me review in more detail when I have some time.  I may reserve the right to re-arrange a few things after approving and merging.  :)

**Comment by faisalhusain007** [comment]
> OK, let me review in more detail when I have some time. I may reserve the right to re-arrange a few things after approving and merging. :)

Sure, to be honest I am an ameture at python, my first look was this time last year I guess when I saw this amazing project, to be fair with your encouragement I managed to start taking my first baby steps. Thanks for that.

**Comment by nebhead** [comment]
> Sure, to be honest I am an ameture at python, my first look was this time last year I guess when I saw this amazing project, to be fair with your encouragement I managed to start taking my first baby steps. Thanks for that.

Oh no worries!  Your code is just fine.  :)  I'm just trying to make some larger architectural decisions and need some time to think about it.  Regardless, keep on learning!  You are doing great.

**Comment by faisalhusain007** [comment]
Just an update not sure if I mentioned it before,  IO pins for the DC fan are 26 for PWM and 19 for the RPM input.

**Comment by faisalhusain007** [comment]
I am going to close this, not ready, testing in the real environment found I need to change any things .... Will re submit a pull request when near finishing ....Sorry

**Comment by nebhead** [comment]
Oh no problem at all.  I've been super busy at work recently and haven't had much time to work on this project.  I'm hoping to get back to it soon so that I can help with the DC fan stuff.  

Internal thoughts:  I wish I had a test platform that I could play around with without fear of wrecking my actual grill.  Maybe I should look around on Craigslist or something for a cheap pellet grill that I can just use as my tester. :)

**Pull request closed without merging**
