### PR TITLE
Added More Status Items to Display

### PR DESCRIPTION
**Pull request by nebhead**
Per a request for enhancement, added more information for status to the display.  The display is extensible in that it can take more than just the temperature data, so that future devices can provide a more rich status.  The current SSD1306 display will now display status for the Fan (picture of a fan in the upper left), Igniter (picture of a flame in the middle left), Notifications (picture of a bell in the upper right), and Auger (picture of arrows in the middle right).  Also, the bottom of the screen displays the current mode in plain text.

### CODE REVIEW

**Comment by slauzon** [comment]
Updated and tested.  Looks like the display does inform the user of the status, but it's indicated by the letters F, I, and A instead of icons.  Also, it looks like the mode status overlaps the temperature at least on my screen.

**Comment by nebhead** [comment]
Oh no!  Something weird happened in my merge and all the changes were lost.  :(  Let me try that again.

**Comment by nebhead** [comment]
OK, pushed the update.  I think what happened was that it I accidentally moved to the main branch, and GitKraken automatically stashed my changes.  Anyway, it should be fixed now.  Give it another go.

**Comment by slauzon** [comment]
Success!  Icons are there now, but looks like we'll still need to make some adjustments to placement.  At the moment the only icons that are visible are the fan and fire.

**Comment by slauzon** [comment]
Success!  Looks good.

**Comment by nebhead** [comment]
Woohoo!!  I think it's looking pretty good, but given that this is just the initial attempt, could use a bit of tweaking.  

That said, I've ordered a new display from Amazon (https://www.amazon.com/gp/product/B07KPDVY6T) that I might add to the project at a later date and these changes will definitely help with providing more options for display status.  Looking at adding a new module to support the new display.

**Pull request merged**
